import type { Theme, ThemeColors } from "./theme-types";
import { SKINS } from "./theme-skins";

/**
 * Built-in theme catalog.
 *
 * Each preset is a 12-color seed (see {@link ThemeColors}). The ESO Gold base
 * theme reproduces the app's original `:root` palette; every other theme was
 * designed and contrast-verified (WCAG) to stay legible against the always-dark
 * component layer.
 */

/** The factory-default theme everyone gets until they explicitly pick another. */
export const DEFAULT_THEME_ID = "nordic-runestone";

/** Bump to forcibly reset EVERY user's active theme to the current
 * {@link DEFAULT_THEME_ID} once on next launch — overriding any theme they had
 * previously chosen. After the reset they keep full control of the picker; a
 * stored version marker stops it from re-applying on later launches.
 * v1 — move everyone onto Nordic Runestone.
 * Lives here (store-free) so it is shared by the theme manager AND the pre-paint
 * boot script's FORCED_VERSION copy (kept in sync by theme-boot.test.ts). */
export const FORCED_DEFAULT_VERSION = 1;

/** The "bare" theme whose colors equal the authored `:root` values in index.css.
 * It is special-cased on apply (overrides are CLEARED rather than set) and stores
 * nothing in the pre-paint boot mirror. Kept distinct from {@link DEFAULT_THEME_ID}:
 * the factory default can be any theme, but only this one matches `:root`. */
export const ROOT_THEME_ID = "eso-gold";

/** Order categories appear in the gallery. Unknown categories sort last.
 * Elder Scrolls (the deluxe textured art themes) lead; the ESO bucket holds the
 * signature default plus the faction/lore color palettes. */
export const CATEGORY_ORDER = [
  "Elder Scrolls",
  "ESO",
  "Editor Classics",
  "Neon",
  "Nature",
  "Gemstone",
  "Metal",
  "Minimal",
  "Custom",
] as const;

const seed = (c: ThemeColors) => c;

/** The ESO Gold base theme — matches the authored `:root` (ESO-gold-on-navy)
 * palette exactly, so applying it clears overrides rather than setting them. */
export const ROOT_THEME: Theme = {
  id: ROOT_THEME_ID,
  name: "ESO Gold",
  description: "The signature Kalpa look — ESO gold over deep navy slate.",
  category: "ESO",
  colors: seed({
    bgBase: "#060c18",
    background: "#0b1220",
    surface: "#0f172a",
    foreground: "#e5e7eb",
    mutedForeground: "#94a3b8",
    primary: "#c4a44a",
    primaryForeground: "#0b1220",
    accent: "#38bdf8",
    border: "#1f2937",
    orb1: "#c4a44a",
    orb2: "#38bdf8",
    orb3: "#6366f1",
  }),
};

/** Designer-generated, contrast-verified themes. */
const GENERATED_THEMES: Theme[] = [
  {
    id: "daedric-crimson",
    name: "Daedric Crimson",
    description: "Infernal red fire raging across cooling obsidian, the forge of Molag Bal.",
    category: "ESO",
    colors: {
      bgBase: "#070203",
      background: "#16060a",
      surface: "#260a10",
      foreground: "#ffe6e1",
      mutedForeground: "#d68f8c",
      primary: "#ff3b3b",
      primaryForeground: "#1c0203",
      accent: "#ff8a3d",
      border: "#43151c",
      orb1: "#d11414",
      orb2: "#ff6b1f",
      orb3: "#6e0d22",
    },
  },
  {
    id: "coldharbour-frost",
    name: "Coldharbour",
    description:
      "A sickly desaturated cyan glow bleeding through the cold grey-black of the soul prison.",
    category: "ESO",
    colors: {
      bgBase: "#030608",
      background: "#071218",
      surface: "#0c1f29",
      foreground: "#dcf0f6",
      mutedForeground: "#84b0bd",
      primary: "#3fc6dd",
      primaryForeground: "#02141b",
      accent: "#67e2f5",
      border: "#173744",
      orb1: "#1592ac",
      orb2: "#2a8fa6",
      orb3: "#0e3a52",
    },
  },
  {
    id: "apocrypha-ink",
    name: "Apocrypha",
    description: "Black ink and toxic green-gold sigils, the forbidden libraries of Hermaeus Mora.",
    category: "ESO",
    colors: {
      bgBase: "#040603",
      background: "#0a0f06",
      surface: "#11190b",
      foreground: "#ecf4d6",
      mutedForeground: "#9fb37e",
      primary: "#aee61f",
      primaryForeground: "#0a1003",
      accent: "#e3c83a",
      border: "#243016",
      orb1: "#7eb50f",
      orb2: "#cba81f",
      orb3: "#2d4514",
    },
  },
  {
    id: "nightblade-twilight",
    name: "Nightblade Twilight",
    description:
      "Violet-magenta shadowfire over assassin's charcoal, the moment before the strike.",
    category: "ESO",
    colors: {
      bgBase: "#06030b",
      background: "#0f0817",
      surface: "#181028",
      foreground: "#f0e4f9",
      mutedForeground: "#ac95c4",
      primary: "#b35cff",
      primaryForeground: "#0f0218",
      accent: "#f255cf",
      border: "#2d1d44",
      orb1: "#9b30f0",
      orb2: "#e01ab0",
      orb3: "#341457",
    },
  },
  {
    id: "blood-matron",
    name: "Blood Matron",
    description: "Muted blood red and weathered bone, the gothic hunger of the vampire courts.",
    category: "ESO",
    colors: {
      bgBase: "#060304",
      background: "#140a0c",
      surface: "#211316",
      foreground: "#f3e2dd",
      mutedForeground: "#bd9b96",
      primary: "#e64b56",
      primaryForeground: "#1c0405",
      accent: "#dcc498",
      border: "#37232a",
      orb1: "#a31c26",
      orb2: "#bfa472",
      orb3: "#4a131c",
    },
  },
  {
    id: "aldmeri-dominion",
    name: "Aldmeri Dominion",
    description: "Regal high-elf gold crowned with living emerald over a deep forest dark.",
    category: "ESO",
    colors: {
      bgBase: "#070a06",
      background: "#0d1409",
      surface: "#152213",
      foreground: "#f6f2dc",
      mutedForeground: "#aec097",
      primary: "#ecca52",
      primaryForeground: "#1a1605",
      accent: "#3fd693",
      border: "#2c3a1f",
      orb1: "#e6c33f",
      orb2: "#2fcf8f",
      orb3: "#7e9433",
    },
  },
  {
    id: "daggerfall-covenant",
    name: "Daggerfall Covenant",
    description: "Royal sapphire heraldry edged in covenant gold over a midnight blue keep.",
    category: "ESO",
    colors: {
      bgBase: "#04060f",
      background: "#080f22",
      surface: "#0f1c39",
      foreground: "#eef3fc",
      mutedForeground: "#94a7cd",
      primary: "#3d86ff",
      primaryForeground: "#03060f",
      accent: "#f0c84e",
      border: "#1d3056",
      orb1: "#2f6ff5",
      orb2: "#f0c33f",
      orb3: "#1d3fad",
    },
  },
  {
    id: "ebonheart-pact",
    name: "Ebonheart Pact",
    description: "Harsh Pact crimson set against cold slate iron, martial and unyielding.",
    category: "ESO",
    colors: {
      bgBase: "#080506",
      background: "#150c0e",
      surface: "#221619",
      foreground: "#f5ece9",
      mutedForeground: "#c0a6a6",
      primary: "#ef3f4b",
      primaryForeground: "#1c0406",
      accent: "#94afc6",
      border: "#3a2429",
      orb1: "#e02633",
      orb2: "#7fa0bd",
      orb3: "#6b3036",
    },
  },
  {
    id: "meridias-light",
    name: "Meridia's Light",
    description:
      "Radiant teal-white luminescence and holy gold flooding a deep teal-black sanctum.",
    category: "ESO",
    colors: {
      bgBase: "#020e0d",
      background: "#04201d",
      surface: "#093029",
      foreground: "#e6fcf6",
      mutedForeground: "#83c6bd",
      primary: "#26eecb",
      primaryForeground: "#02201a",
      accent: "#f6da5e",
      border: "#15433d",
      orb1: "#1ad9bd",
      orb2: "#f3d44a",
      orb3: "#149285",
    },
  },
  {
    id: "hist-sap",
    name: "Hist Sap",
    description: "Warm amber sap weeping through swamp green over a dark Argonian bog.",
    category: "ESO",
    colors: {
      bgBase: "#0c0703",
      background: "#180f06",
      surface: "#26190c",
      foreground: "#f7eed8",
      mutedForeground: "#c0a87e",
      primary: "#f0a82f",
      primaryForeground: "#1e1203",
      accent: "#76c052",
      border: "#3b2a14",
      orb1: "#e89a26",
      orb2: "#5fb842",
      orb3: "#956c22",
    },
  },
  {
    id: "dracula",
    name: "Dracula",
    description: "The iconic purple-and-cyan vampire palette glowing over deep slate dark.",
    category: "Editor Classics",
    colors: {
      bgBase: "#191a21",
      background: "#21222c",
      surface: "#282a36",
      foreground: "#f8f8f2",
      mutedForeground: "#9ca0b0",
      primary: "#bd93f9",
      primaryForeground: "#191a21",
      accent: "#8be9fd",
      border: "#44475a",
      orb1: "#bd93f9",
      orb2: "#8be9fd",
      orb3: "#ff79c6",
    },
  },
  {
    id: "nord",
    name: "Nord",
    description: "Arctic, frost-blue polar night with calm cool steel surfaces.",
    category: "Editor Classics",
    colors: {
      bgBase: "#242933",
      background: "#2e3440",
      surface: "#3b4252",
      foreground: "#eceff4",
      mutedForeground: "#abb2c0",
      primary: "#88c0d0",
      primaryForeground: "#2e3440",
      accent: "#81a1c1",
      border: "#4c566a",
      orb1: "#88c0d0",
      orb2: "#81a1c1",
      orb3: "#a3be8c",
    },
  },
  {
    id: "tokyo-night",
    name: "Tokyo Night",
    description: "Neon Shinjuku blues and violets over an inky midnight skyline.",
    category: "Editor Classics",
    colors: {
      bgBase: "#16161e",
      background: "#1a1b26",
      surface: "#24283b",
      foreground: "#c0caf5",
      mutedForeground: "#9099c2",
      primary: "#7aa2f7",
      primaryForeground: "#16161e",
      accent: "#bb9af7",
      border: "#3b4261",
      orb1: "#7aa2f7",
      orb2: "#bb9af7",
      orb3: "#7dcfff",
    },
  },
  {
    id: "catppuccin-mocha",
    name: "Catppuccin Mocha",
    description: "Soft pastel mauve and blue on the cozy darkest Mocha base.",
    category: "Editor Classics",
    colors: {
      bgBase: "#11111b",
      background: "#1e1e2e",
      surface: "#313244",
      foreground: "#cdd6f4",
      mutedForeground: "#a6adc8",
      primary: "#cba6f7",
      primaryForeground: "#11111b",
      accent: "#89b4fa",
      border: "#45475a",
      orb1: "#cba6f7",
      orb2: "#89b4fa",
      orb3: "#f5c2e7",
    },
  },
  {
    id: "one-dark",
    name: "One Dark (Atom)",
    description: "Atom's signature blue-and-magenta scheme on warm graphite gray.",
    category: "Editor Classics",
    colors: {
      bgBase: "#21252b",
      background: "#282c34",
      surface: "#31363f",
      foreground: "#dfe3ea",
      mutedForeground: "#9da5b4",
      primary: "#61afef",
      primaryForeground: "#21252b",
      accent: "#c678dd",
      border: "#3e4451",
      orb1: "#61afef",
      orb2: "#c678dd",
      orb3: "#98c379",
    },
  },
  {
    id: "gruvbox-dark",
    name: "Gruvbox Dark",
    description: "Warm retro earth tones with a glowing amber primary on roasted-coffee panels.",
    category: "Editor Classics",
    colors: {
      bgBase: "#1d2021",
      background: "#282828",
      surface: "#3c3836",
      foreground: "#ebdbb2",
      mutedForeground: "#bdae93",
      primary: "#fabd2f",
      primaryForeground: "#1d2021",
      accent: "#83a598",
      border: "#504945",
      orb1: "#fabd2f",
      orb2: "#83a598",
      orb3: "#b8bb26",
    },
  },
  {
    id: "rose-pine",
    name: "Rosé Pine",
    description: "Soft muted rose and pine on a dusky violet canvas — cozy and refined.",
    category: "Editor Classics",
    colors: {
      bgBase: "#191724",
      background: "#1f1d2e",
      surface: "#26233a",
      foreground: "#e0def4",
      mutedForeground: "#908caa",
      primary: "#ebbcba",
      primaryForeground: "#191724",
      accent: "#9ccfd8",
      border: "#403d52",
      orb1: "#ebbcba",
      orb2: "#9ccfd8",
      orb3: "#c4a7e7",
    },
  },
  {
    id: "solarized-dark",
    name: "Solarized Dark",
    description: "Ethan Schoonover's precision palette: teal-tinted base with amber and blue.",
    category: "Editor Classics",
    colors: {
      bgBase: "#002028",
      background: "#002b36",
      surface: "#073642",
      foreground: "#eee8d5",
      mutedForeground: "#93a1a1",
      primary: "#b58900",
      primaryForeground: "#002b36",
      accent: "#268bd2",
      border: "#0d4a58",
      orb1: "#b58900",
      orb2: "#268bd2",
      orb3: "#2aa198",
    },
  },
  {
    id: "monokai-pro",
    name: "Monokai Pro",
    description: "Iconic vivid yellow and cyan on near-black graphite — the classic hacker glow.",
    category: "Editor Classics",
    colors: {
      bgBase: "#19181a",
      background: "#221f22",
      surface: "#2d2a2e",
      foreground: "#fcfcfa",
      mutedForeground: "#939293",
      primary: "#ffd866",
      primaryForeground: "#221f22",
      accent: "#78dce8",
      border: "#403e41",
      orb1: "#ffd866",
      orb2: "#78dce8",
      orb3: "#ff6188",
    },
  },
  {
    id: "everforest-dark",
    name: "Everforest Dark",
    description: "Soft mossy greens on a deep forest floor — gentle, organic, low-strain.",
    category: "Editor Classics",
    colors: {
      bgBase: "#272e33",
      background: "#2d353b",
      surface: "#374247",
      foreground: "#d3c6aa",
      mutedForeground: "#a6b0a0",
      primary: "#a7c080",
      primaryForeground: "#272e33",
      accent: "#7fbbb3",
      border: "#4a555b",
      orb1: "#a7c080",
      orb2: "#7fbbb3",
      orb3: "#dbbc7f",
    },
  },
  {
    id: "synthwave-outrun",
    name: "Synthwave Outrun",
    description: "Hot magenta and electric cyan streak across a deep violet horizon at dusk.",
    category: "Neon",
    colors: {
      bgBase: "#120a24",
      background: "#1a0f33",
      surface: "#251748",
      foreground: "#f4ecff",
      mutedForeground: "#b39ad9",
      primary: "#ff2e97",
      primaryForeground: "#1a0024",
      accent: "#22d3ee",
      border: "#382560",
      orb1: "#ff2e97",
      orb2: "#22d3ee",
      orb3: "#7c3aed",
    },
  },
  {
    id: "night-city",
    name: "Night City",
    description: "Cyberpunk neon yellow and cyan flicker over an inky black-teal sprawl.",
    category: "Neon",
    colors: {
      bgBase: "#03100f",
      background: "#06181a",
      surface: "#0b2528",
      foreground: "#eafcff",
      mutedForeground: "#7fc9cf",
      primary: "#fde047",
      primaryForeground: "#1a1500",
      accent: "#22d3ee",
      border: "#10383c",
      orb1: "#fde047",
      orb2: "#22d3ee",
      orb3: "#06b6d4",
    },
  },
  {
    id: "vaporwave-dream",
    name: "Vaporwave Dream",
    description: "Pastel pink and soft teal float dreamily over a dark indigo void.",
    category: "Neon",
    colors: {
      bgBase: "#0e0a26",
      background: "#161232",
      surface: "#211c47",
      foreground: "#fdeef7",
      mutedForeground: "#b6a9d6",
      primary: "#ff8fcf",
      primaryForeground: "#2a0a1f",
      accent: "#5ce8d8",
      border: "#322a5e",
      orb1: "#ff8fcf",
      orb2: "#5ce8d8",
      orb3: "#a78bfa",
    },
  },
  {
    id: "matrix-terminal",
    name: "Matrix Terminal",
    description: "Phosphor green rains down a pitch-black CRT terminal.",
    category: "Neon",
    colors: {
      bgBase: "#020a05",
      background: "#04140a",
      surface: "#082011",
      foreground: "#d6ffe0",
      mutedForeground: "#5fb87a",
      primary: "#22e34a",
      primaryForeground: "#00160a",
      accent: "#7dffa0",
      border: "#0e3220",
      orb1: "#22e34a",
      orb2: "#7dffa0",
      orb3: "#0a7d3a",
    },
  },
  {
    id: "miami-neon",
    name: "Miami Neon",
    description: "Hot pink and aqua signage blaze against a deep midnight-navy beachfront.",
    category: "Neon",
    colors: {
      bgBase: "#06122e",
      background: "#0a1b40",
      surface: "#102656",
      foreground: "#eaf3ff",
      mutedForeground: "#86a5d6",
      primary: "#ff4d9e",
      primaryForeground: "#2a0016",
      accent: "#2ce8e0",
      border: "#1a3670",
      orb1: "#ff4d9e",
      orb2: "#2ce8e0",
      orb3: "#5b8def",
    },
  },
  {
    id: "deep-forest",
    name: "Deep Forest",
    description:
      "Mossy canopy light filtering through ancient pine, damp earth, and quiet undergrowth.",
    category: "Nature",
    colors: {
      bgBase: "#070d0a",
      background: "#0b1410",
      surface: "#12201a",
      foreground: "#e3f0e4",
      mutedForeground: "#9bb6a4",
      primary: "#4ca771",
      primaryForeground: "#04130a",
      accent: "#5fd0a8",
      border: "#1d3329",
      orb1: "#4ca771",
      orb2: "#5fd0a8",
      orb3: "#2d6a4f",
    },
  },
  {
    id: "ocean-abyss",
    name: "Ocean Abyss",
    description:
      "Crushing midnight-zone blue pierced by the cold teal flicker of bioluminescent life.",
    category: "Nature",
    colors: {
      bgBase: "#040a12",
      background: "#07121e",
      surface: "#0c1d2e",
      foreground: "#dcecf6",
      mutedForeground: "#8fb0c6",
      primary: "#2bb8c9",
      primaryForeground: "#02141a",
      accent: "#4fd6e8",
      border: "#163349",
      orb1: "#2bb8c9",
      orb2: "#4fd6e8",
      orb3: "#1f6f9c",
    },
  },
  {
    id: "volcanic-ember",
    name: "Volcanic Ember",
    description:
      "Cooling charcoal crust split by veins of molten lava and the glow of fresh embers.",
    category: "Nature",
    colors: {
      bgBase: "#0d0807",
      background: "#160d0a",
      surface: "#221512",
      foreground: "#f3e6df",
      mutedForeground: "#c0a193",
      primary: "#ff6b35",
      primaryForeground: "#1a0700",
      accent: "#ffae57",
      border: "#3a221a",
      orb1: "#ff6b35",
      orb2: "#ff3d2e",
      orb3: "#c43a14",
    },
  },
  {
    id: "aurora-borealis",
    name: "Aurora Borealis",
    description: "Ribbons of electric green and violet drifting across a frozen polar-night sky.",
    category: "Nature",
    colors: {
      bgBase: "#050912",
      background: "#091223",
      surface: "#101d36",
      foreground: "#e0ecf7",
      mutedForeground: "#94aacb",
      primary: "#46e6a0",
      primaryForeground: "#02160d",
      accent: "#a585f0",
      border: "#1f3252",
      orb1: "#46e6a0",
      orb2: "#a585f0",
      orb3: "#2f6bd6",
    },
  },
  {
    id: "nebula-galaxy",
    name: "Nebula Galaxy",
    description: "Swirling cosmic dust glowing in purple, pink, and deep-blue across the void.",
    category: "Nature",
    colors: {
      bgBase: "#0a0714",
      background: "#120c20",
      surface: "#1d1432",
      foreground: "#ece4f7",
      mutedForeground: "#b09cc9",
      primary: "#b46bff",
      primaryForeground: "#0f041c",
      accent: "#ff7ad1",
      border: "#2f2150",
      orb1: "#b46bff",
      orb2: "#ff7ad1",
      orb3: "#5b6bff",
    },
  },
  {
    id: "carbon",
    name: "Carbon",
    description: "Neutral graphite greys lit by a single quiet steel-blue accent.",
    category: "Minimal",
    colors: {
      bgBase: "#0d0e10",
      background: "#141518",
      surface: "#1c1e22",
      foreground: "#e8eaed",
      mutedForeground: "#9aa0a8",
      primary: "#6ba3d6",
      primaryForeground: "#06090c",
      accent: "#7fb8e6",
      border: "#2a2d33",
      orb1: "#3b6a99",
      orb2: "#4a7ba8",
      orb3: "#3a3f47",
    },
  },
  {
    id: "pure-black-oled",
    name: "Pure Black OLED",
    description: "True-black canvas with crisp white type and one cold blue spark.",
    category: "Minimal",
    colors: {
      bgBase: "#000000",
      background: "#050505",
      surface: "#0e0e0e",
      foreground: "#fbfbfb",
      mutedForeground: "#9c9c9c",
      primary: "#ffffff",
      primaryForeground: "#000000",
      accent: "#8ab4ff",
      border: "#1c1c1c",
      orb1: "#2a2a2a",
      orb2: "#3a4a6a",
      orb3: "#1a1a1a",
    },
  },
  {
    id: "midnight-slate",
    name: "Midnight Slate",
    description: "Calm blue-grey twilight, soft and unhurried.",
    category: "Minimal",
    colors: {
      bgBase: "#0b0e14",
      background: "#11151d",
      surface: "#1a1f29",
      foreground: "#dde3ec",
      mutedForeground: "#929aab",
      primary: "#7a93c4",
      primaryForeground: "#070a0f",
      accent: "#8fa9d8",
      border: "#272d3a",
      orb1: "#3a4a73",
      orb2: "#4a5b88",
      orb3: "#33394a",
    },
  },
  {
    id: "amber-crt",
    name: "Amber CRT Terminal",
    description: "Monochrome amber phosphor glowing on a near-black screen.",
    category: "Minimal",
    colors: {
      bgBase: "#0c0900",
      background: "#130d00",
      surface: "#1c1400",
      foreground: "#ffcf5e",
      mutedForeground: "#c89a3a",
      primary: "#ffb000",
      primaryForeground: "#0c0900",
      accent: "#ffc94d",
      border: "#2e2300",
      orb1: "#7a5400",
      orb2: "#946a00",
      orb3: "#3a2c00",
    },
  },
  {
    id: "ice-mono",
    name: "Ice Mono",
    description: "Cool desaturated blue-whites like frost on dark glass.",
    category: "Minimal",
    colors: {
      bgBase: "#0a0d10",
      background: "#10141a",
      surface: "#191f27",
      foreground: "#e6edf4",
      mutedForeground: "#94a3b3",
      primary: "#a8c7e0",
      primaryForeground: "#070a0d",
      accent: "#bcd8ee",
      border: "#262e38",
      orb1: "#4a6b85",
      orb2: "#5e8099",
      orb3: "#374350",
    },
  },
  {
    id: "amethyst-royale",
    name: "Amethyst Royale",
    description:
      "Deep violet shadows lit by a glowing purple gem with a cool sapphire-blue sparkle.",
    category: "Gemstone",
    colors: {
      bgBase: "#0f0a16",
      background: "#14101f",
      surface: "#1d1730",
      foreground: "#efe9f7",
      mutedForeground: "#b3a4c9",
      primary: "#a570f0",
      primaryForeground: "#160a26",
      accent: "#7cc4f5",
      border: "#2e2545",
      orb1: "#9b5cf0",
      orb2: "#5aa8e0",
      orb3: "#c77dd6",
    },
  },
  {
    id: "emerald-vault",
    name: "Emerald Vault",
    description:
      "A near-black forest of malachite green crowned by a vivid emerald and a teal glint.",
    category: "Gemstone",
    colors: {
      bgBase: "#06120d",
      background: "#0a1812",
      surface: "#11241b",
      foreground: "#e6f5ec",
      mutedForeground: "#9bc7ae",
      primary: "#2fd396",
      primaryForeground: "#04150d",
      accent: "#5fd0e0",
      border: "#1d3a2c",
      orb1: "#27c98c",
      orb2: "#4fbfd0",
      orb3: "#7ad98f",
    },
  },
  {
    id: "sapphire-depths",
    name: "Sapphire Depths",
    description:
      "Midnight indigo waters where a brilliant blue stone catches a cyan flash of light.",
    category: "Gemstone",
    colors: {
      bgBase: "#070d18",
      background: "#0b1322",
      surface: "#121d33",
      foreground: "#e7eefc",
      mutedForeground: "#9db4d8",
      primary: "#4d8df5",
      primaryForeground: "#05101f",
      accent: "#54d0e8",
      border: "#1f2d48",
      orb1: "#3f7ff0",
      orb2: "#3fc8e8",
      orb3: "#7d8ff5",
    },
  },
  {
    id: "rose-gold-noir",
    name: "Rose Gold Noir",
    description: "Warm pink-gold light softly blooming over a deep mauve-black velvet dark.",
    category: "Metal",
    colors: {
      bgBase: "#150b10",
      background: "#1c1016",
      surface: "#281820",
      foreground: "#f7ebef",
      mutedForeground: "#ceaab4",
      primary: "#e89aa0",
      primaryForeground: "#22090e",
      accent: "#e0b878",
      border: "#3a2730",
      orb1: "#e88f9a",
      orb2: "#dcb072",
      orb3: "#c98699",
    },
  },
  {
    id: "copper-patina",
    name: "Copper Patina",
    description: "Oxidized teal-green bronze warmed by the glow of freshly polished copper.",
    category: "Metal",
    colors: {
      bgBase: "#08120f",
      background: "#0c1815",
      surface: "#13241f",
      foreground: "#e4f3ed",
      mutedForeground: "#9ac5b6",
      primary: "#d98a5a",
      primaryForeground: "#1a0d05",
      accent: "#3fcab0",
      border: "#1f3a31",
      orb1: "#d4824f",
      orb2: "#35c2a6",
      orb3: "#5fae8e",
    },
  },
  {
    id: "elder-scroll-ancient-tome",
    name: "Elder Scroll",
    description:
      "An ancient tome bound in dark sepia parchment, inked with antique gold. Warm, scholarly, candle-lit lamplight glowing through aged vellum — the deep moody amber of a Scroll waiting to be read.",
    category: "Elder Scrolls",
    colors: {
      bgBase: "#120c06",
      background: "#1a1107",
      surface: "#241809",
      foreground: "#f0e2c4",
      mutedForeground: "#c2a878",
      primary: "#e0b54a",
      primaryForeground: "#1a1107",
      accent: "#e8c97a",
      border: "#473311",
      orb1: "#a87c2a",
      orb2: "#6b4a18",
      orb3: "#c99a3a",
    },
    skin: SKINS["elder-scroll-ancient-tome"],
  },
  {
    id: "daedric-obsidian",
    name: "Daedric Obsidian",
    description:
      "Black volcanic glass laced with molten lava veins, pulsing in the dark of Oblivion. Searing Daedric-rune orange against near-black obsidian — menacing, fiery, forged in a Deadlands smithy.",
    category: "Elder Scrolls",
    colors: {
      bgBase: "#0a0506",
      background: "#120708",
      surface: "#1c0c0d",
      foreground: "#f3dcd8",
      mutedForeground: "#c08a82",
      primary: "#ff5a2c",
      primaryForeground: "#160707",
      accent: "#ff7a4d",
      border: "#3e1614",
      orb1: "#e23a1e",
      orb2: "#7a160e",
      orb3: "#ff6a30",
    },
    skin: SKINS["daedric-obsidian"],
  },
  {
    id: "dwemer-brass",
    name: "Dwemer Brass",
    description:
      "Dark bronze and aged brass machinery, warm metal touched by verdigris where ancient steam once breathed. A lost Dwemer ruin — golden cogs against patinated teal-green corrosion, mechanical and arcane.",
    category: "Elder Scrolls",
    colors: {
      bgBase: "#0c0a06",
      background: "#14110a",
      surface: "#1f1a0f",
      foreground: "#ecdcb4",
      mutedForeground: "#bda878",
      primary: "#d4a23c",
      primaryForeground: "#16120a",
      accent: "#5fd4b0",
      border: "#3d3318",
      orb1: "#b8862c",
      orb2: "#2f9c7e",
      orb3: "#cf9a38",
    },
    skin: SKINS["dwemer-brass"],
  },
  {
    id: "ayleid-welkynd",
    name: "Ayleid Welkynd",
    description:
      "Dark slate ruins lit by glowing welkynd crystals — luminous teal-white facets humming with ancient Ayleid magic. Cold, ethereal, crystalline; the eerie blue-green glow of a buried Ayleid well in the dark.",
    category: "Elder Scrolls",
    colors: {
      bgBase: "#06090c",
      background: "#0a1016",
      surface: "#101a22",
      foreground: "#dcf2f4",
      mutedForeground: "#88b4bd",
      primary: "#3ee0d6",
      primaryForeground: "#06181a",
      accent: "#6ae8ff",
      border: "#1d3540",
      orb1: "#22b0c8",
      orb2: "#1a7a96",
      orb3: "#4fd8e0",
    },
    skin: SKINS["ayleid-welkynd"],
  },
  {
    id: "sithis-brotherhood",
    name: "Sithis",
    description:
      "The Void made material — a near-black abyss breathing cold blue-grey, with blood-crimson ritual linework and bone-ash neutrals. The Black Hand opens off-center within a thorned Night Mother rose-vine field; crossed Blades of Woe meet in a node at every junction; smoke rises and light dies at the edges.",
    category: "Elder Scrolls",
    colors: {
      bgBase: "#070809",
      background: "#0a0c0e",
      surface: "#11141a",
      foreground: "#e8e2d8",
      mutedForeground: "#9a958c",
      primary: "#ef4452",
      primaryForeground: "#1c0406",
      accent: "#e84252",
      border: "#221a1c",
      orb1: "#7a0f18",
      orb2: "#1a2630",
      orb3: "#3a0a10",
    },
    skin: SKINS["sithis-brotherhood"],
  },
  {
    id: "apocrypha-mora",
    name: "Hermaeus Mora",
    description:
      "Forbidden knowledge bleeding from the black-green void of Hermaeus Mora — sickly chartreuse ink writhes across ink-stained vellum, watched by unblinking eyes.",
    category: "Elder Scrolls",
    colors: {
      bgBase: "#040806",
      background: "#0a120c",
      surface: "#0f1c13",
      foreground: "#dff0d2",
      mutedForeground: "#8aa07c",
      primary: "#b4d12e",
      primaryForeground: "#0a1206",
      accent: "#3ec99a",
      border: "#234027",
      orb1: "#9fc41f",
      orb2: "#2fb389",
      orb3: "#16432e",
    },
    skin: SKINS["apocrypha-mora"],
  },
  {
    id: "clockwork-city",
    name: "Clockwork City",
    description:
      "Sotha Sil's divine machine as a living gear-train: real involute-toothed brass wheels meshing at true tangent points, a dominant faceted Clockwork-God core ringed by a graduated astronomical scale, apostle-cyan energy nodes firing exactly where teeth transmit force, recessed bronze idlers receding into furnace-lit depth. Mathematical, sacred-mechanical, immaculate.",
    category: "Elder Scrolls",
    colors: {
      bgBase: "#0d0a07",
      background: "#120d09",
      surface: "#1c150e",
      foreground: "#f3e7cf",
      mutedForeground: "#a8946f",
      primary: "#c4a44a",
      primaryForeground: "#1a1209",
      accent: "#3fd0e0",
      border: "#3a2c1a",
      orb1: "#c4a44a",
      orb2: "#3fd0e0",
      orb3: "#7a5a26",
    },
    skin: SKINS["clockwork-city"],
  },
  {
    id: "nordic-runestone",
    name: "Nordic Runestone",
    description:
      "Skyrim-carved Nordic runestone — weathered grey granite incised with torch-lit amber Elder Futhark runes and a true over-under Urnes serpent plait, with a steel-blue cold-stone counterpoint and a valknut focal, lit against deep stone shadow.",
    category: "Elder Scrolls",
    colors: {
      bgBase: "#16181b",
      background: "#191c20",
      surface: "#23272d",
      foreground: "#e7e2d4",
      mutedForeground: "#9a9b96",
      primary: "#d2a14e",
      primaryForeground: "#1a1611",
      accent: "#6fa8c4",
      border: "#3a3f46",
      orb1: "#d2a14e",
      orb2: "#5d8aa8",
      orb3: "#4a5a52",
    },
    skin: SKINS["nordic-runestone"],
  },
];

/** All built-in themes. The ESO Gold base leads the gallery as the signature
 * look; the factory default ({@link DEFAULT_THEME}) may be any of them. */
export const BUILTIN_THEMES: Theme[] = [ROOT_THEME, ...GENERATED_THEMES];

export const BUILTIN_THEME_IDS = new Set(BUILTIN_THEMES.map((t) => t.id));

/** The resolved factory-default theme object (see {@link DEFAULT_THEME_ID}).
 * Falls back to the ESO Gold base if the id is ever mistyped. */
export const DEFAULT_THEME: Theme =
  BUILTIN_THEMES.find((t) => t.id === DEFAULT_THEME_ID) ?? ROOT_THEME;
